config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'urls#new'

  post '/', to: 'urls#create'
  get '/:token', to: 'urls#show', as: :show_url
  get '/:token/info', to: 'urls#info'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/tokens.rb
module Tokens
  private

  def generate_token
    tokens = Url.pluck(:token)

    loop do
      token = SecureRandom.hex(8)
      return self.token = token unless tokens.include?(token)
    end
  end
end

app/models/url.rb
class Url < ApplicationRecord
  include Tokens

  has_many :url_logs

  before_create :generate_token
  validates_uniqueness_of :full_path
  validates_presence_of :full_path
  validate :url_full_path

  private

  def url_full_path
    self.errors.add :full_path unless full_path =~ URI::regexp
  end
end

app/models/url_log.rb
class UrlLog < ApplicationRecord
  belongs_to :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[show info]

  def new
    @url = Url.new
    @urls = Url.all
  end

  def create
    @url = Url.new(url_params)

    if @url.save
      flash[:notice] = 'Url successfully created'
      redirect_to root_path
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append('errors', partial: 'shared/error_messages', locals: { object: @url }) }
        format.html { render :new }
      end
    end
  end

  def show
    create_log

    render 'redirect_external'
  end

  def info; end

  private

  def url_params
    params.require(:url).permit(:full_path)
  end

  def set_url
    @url = Url.find_by_token(params[:token])
  end

  def create_log
    @url.url_logs.create(ip: request.remote_ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestURL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<turbo-stream action="append" target="errors">
  <template>
    <div class="error-message">
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </template>
</turbo-stream>

app/views/urls/_list.html.erb
<% @urls.each do |url| %>
  <div>
    <%= link_to url.token, show_url_path(url.token) %>
  </div>
<% end %>

app/views/urls/info.html.erb
<div>
  <strong>Url:</strong> <%= link_to @url.full_path, @url.full_path %>
</div>

<div>
  <strong>Token:</strong> <%= link_to @url.token, show_url_path(@url.token) %>
</div>

<div>
  <strong>List of IPs:</strong>
  <ul>
    <% @url.url_logs.each do |log| %>
      <li><%= log.ip %></li>
    <% end %>
  </ul>
</div>

app/views/urls/new.html.erb
<div id="errors">
  <%= render 'shared/error_messages', object: @url %>
</div>

<%= form_for :url, method: :post do |f| %>
  <%= f.label 'Enter your URL here:' %>
  <%= f.text_field :full_path %>
  <%= f.submit %>
<% end %>

<%= render 'urls/list' if @urls %>

app/views/urls/redirect_external.html.erb
<script>
    window.location.href = '<%= @url.full_path %>';
</script>